In [4]:
!pip3 install tensorflow opencv-python mediapipe scikit-learn matplotlib

  Using cached tensorflow-2.17.0-cp310-cp310-win_amd64.whl (2.0 kB)
  Using cached tensorflow_intel-2.17.0-cp310-cp310-win_amd64.whl (385.0 MB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
  Using cached h5py-3.11.0-cp310-cp310-win_amd64.whl (3.0 MB)
  Using cached keras-3.4.1-py3-none-any.whl (1.1 MB)
  Using cached requests-2.32.3-py3-none-any.whl (64 kB)
  Using cached gast-0.6.0-py3-none-any.whl (21 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached tensorboard-2.17.0-py3-none-any.whl (5.5 MB)
  Using cached grpcio-1.65.4-cp310-cp310-win_amd64.whl (4.1 MB)
  Using cached optree-0.12.1-cp310-cp310-win_amd64.whl (267 kB)
  Using cached rich-13.7.1-py3-none-any.whl (240 kB)
  Using cached idna-3.7-py3-none-any.whl (66 kB)
  Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
  Using cached werkzeug-3.0


[notice] A new release of pip available: 22.2.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp

In [3]:
mp_holistic=mp.solutions.holistic #holistic model
mp_drawing=mp.solutions.drawing_utils #drawing utils

In [4]:
def mediapipe_detect(image,model):
    image=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
    image.flags.writeable=False
    results=model.process(image)
    image.flags.writeable=True
    image=cv2.cvtColor(image,cv2.COLOR_RGB2BGR)
    return image,results

In [5]:
def draw_landmarks(image,results):
    mp_drawing.draw_landmarks(image,results.face_landmarks,mp_holistic.FACEMESH_TESSELATION)
    mp_drawing.draw_landmarks(image,results.pose_landmarks,mp_holistic.POSE_CONNECTIONS)
    mp_drawing.draw_landmarks(image,results.left_hand_landmarks,mp_holistic.HAND_CONNECTIONS)
    mp_drawing.draw_landmarks(image,results.right_hand_landmarks,mp_holistic.HAND_CONNECTIONS)

In [6]:
def draw_styled_landmarks(image,results):
    # draw face connections
    mp_drawing.draw_landmarks(image,results.face_landmarks,mp_holistic.FACEMESH_TESSELATION,
                              mp_drawing.DrawingSpec(color=(80,110,10),thickness=1,circle_radius=1),
                              mp_drawing.DrawingSpec(color=(80,256,121),thickness=1,circle_radius=1)
                              )
    # draw pose connections
    mp_drawing.draw_landmarks(image,results.pose_landmarks,mp_holistic.POSE_CONNECTIONS,
                              mp_drawing.DrawingSpec(color=(80,22,10),thickness=2,circle_radius=4),
                              mp_drawing.DrawingSpec(color=(80,44,121),thickness=2,circle_radius=2))
    # draw left hand connections
    mp_drawing.draw_landmarks(image,results.left_hand_landmarks,mp_holistic.HAND_CONNECTIONS,
                              mp_drawing.DrawingSpec(color=(121,22,76),thickness=2,circle_radius=4),
                              mp_drawing.DrawingSpec(color=(121,44,250),thickness=2,circle_radius=2))
    # draw right hand connections
    mp_drawing.draw_landmarks(image,results.right_hand_landmarks,mp_holistic.HAND_CONNECTIONS,
                              mp_drawing.DrawingSpec(color=(245,117,66),thickness=2,circle_radius=4),
                              mp_drawing.DrawingSpec(color=(245,66,230),thickness=2,circle_radius=2))

In [7]:
cap=cv2.VideoCapture(0)
# Access mediapipe model
with mp_holistic.Holistic(min_detection_confidence=0.5,min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        # read feed
        ret,frame=cap.read()

        # make detections
        image,results=mediapipe_detect(frame,holistic)
        print(results)

        # draw landmarks
        draw_styled_landmarks(image,results)

        # show to screen
        cv2.imshow("OpenCV Feed",image)

        # break gracefully
        if cv2.waitKey(10) & 0XFF==ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

c:\Users\gk-lenovo\OneDrive\Desktop\Projects\final_year_project\project_code\venv\lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '


<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

In [104]:
frame

array([[[207, 210, 195],
        [205, 208, 193],
        [204, 207, 192],
        ...,
        [198, 201, 193],
        [197, 200, 192],
        [193, 196, 188]],

       [[205, 208, 193],
        [205, 208, 193],
        [205, 208, 193],
        ...,
        [197, 200, 191],
        [196, 199, 190],
        [193, 196, 187]],

       [[202, 206, 191],
        [204, 208, 193],
        [206, 210, 195],
        ...,
        [197, 200, 191],
        [195, 198, 188],
        [193, 196, 186]],

       ...,

       [[111, 121, 125],
        [110, 120, 124],
        [109, 119, 122],
        ...,
        [ 88,  87, 110],
        [ 88,  88, 110],
        [ 87,  88, 109]],

       [[112, 119, 124],
        [111, 119, 123],
        [109, 117, 120],
        ...,
        [ 88,  87, 110],
        [ 89,  89, 111],
        [ 92,  93, 114]],

       [[111, 117, 122],
        [109, 115, 120],
        [109, 115, 117],
        ...,
        [ 89,  88, 111],
        [ 91,  91, 113],
        [ 95,  96, 117]]

In [105]:
results.left_hand_landmarks

In [106]:
results.face_landmarks

landmark {
  x: 0.539997458
  y: 0.412341654
  z: -0.017236162
}
landmark {
  x: 0.539713144
  y: 0.375902772
  z: -0.0469826758
}
landmark {
  x: 0.538099051
  y: 0.38433069
  z: -0.0211508498
}
landmark {
  x: 0.526548743
  y: 0.330460131
  z: -0.0412811525
}
landmark {
  x: 0.538947701
  y: 0.363054603
  z: -0.0516948029
}
landmark {
  x: 0.536771476
  y: 0.344054729
  z: -0.0502856858
}
landmark {
  x: 0.530297
  y: 0.295401335
  z: -0.0323119424
}
landmark {
  x: 0.4582569
  y: 0.296450853
  z: -0.00212707743
}
landmark {
  x: 0.52661258
  y: 0.26131624
  z: -0.0306295119
}
landmark {
  x: 0.525237918
  y: 0.243215516
  z: -0.0353192091
}
landmark {
  x: 0.518223166
  y: 0.173410594
  z: -0.0354576148
}
landmark {
  x: 0.540252388
  y: 0.417879462
  z: -0.01504682
}
landmark {
  x: 0.540128708
  y: 0.420976788
  z: -0.0112409452
}
landmark {
  x: 0.539689481
  y: 0.421281129
  z: -0.00666491129
}
landmark {
  x: 0.54013437
  y: 0.420697927
  z: -0.00497140223
}
landmark {
  x: 0.5

In [107]:
draw_landmarks(frame,results)

In [76]:
# plt.imshow(cv2.cvtColor(frame,cv2.COLOR_BGR2RGB))

In [108]:
pose=[]
for res in results.pose_landmarks.landmark:
    test=np.array([res.x,res.y,res.z,res.visibility])
    pose.append(test)

In [109]:
pose=np.array([[res.x,res.y,res.z,res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(132)
lh=np.array([[res.x,res.y,res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
rh=np.array([[res.x,res.y,res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
face=np.array([[res.x,res.y,res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(1404)

In [110]:
def extract_keypoints(results):
    pose=np.array([[res.x,res.y,res.z,res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    lh=np.array([[res.x,res.y,res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh=np.array([[res.x,res.y,res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    face=np.array([[res.x,res.y,res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)

    return np.concatenate([pose,face,lh,rh])

In [111]:
result_test=extract_keypoints(results)[:5]

In [112]:
result_test

array([ 0.53928214,  0.33489075, -0.74450219,  0.99992406,  0.56336081])

In [113]:
np.save('0',result_test)

In [114]:
np.load('0.npy')

array([ 0.53928214,  0.33489075, -0.74450219,  0.99992406,  0.56336081])

In [115]:
# path for extracted data 
DATA_PATH=os.path.join('MP_DATA')

# actions that we will detect
actions=np.array(["hello","thanks","iloveyou"])

# no. of videos
no_sequence=30

# no. of frames in videos
sequence_length=30

In [116]:
for action in actions:
    for sequence in range(no_sequence):
        try:
            os.makedirs(os.path.join(DATA_PATH,action,str(sequence)))
        except Exception as e:
            print(e)

In [117]:
cap=cv2.VideoCapture(0)
# Access mediapipe model
with mp_holistic.Holistic(min_detection_confidence=0.5,min_tracking_confidence=0.5) as holistic:
    for action in actions:

        for sequence in range(no_sequence):

            for frame_num in range(sequence_length):
                # read feed
                ret,frame=cap.read()

                # make detections
                image,results=mediapipe_detect(frame,holistic)
                print(results)

                # draw landmarks
                draw_styled_landmarks(image,results)

                # apply wait collection logic
                if frame_num==0:
                    cv2.putText(image,"STARTING COLLECTION",(120,200),
                                cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),4,cv2.LINE_AA)
                    cv2.putText(image,"Collecting frames for {} Video Number {}".format(action,sequence),(15,12),
                                cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),1,cv2.LINE_AA)
                    cv2.waitKey(2000)
                
                else:
                    cv2.putText(image,"Collecting frames for {} Video Number {}".format(action,sequence),(15,12),
                                cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),1,cv2.LINE_AA)
                    
                keypoints=extract_keypoints(results)
                npy_path=os.path.join(DATA_PATH,action,str(sequence),str(frame_num))
                np.save(npy_path,keypoints)
                
                
                # show to screen
                cv2.imshow("OpenCV Feed",image)

                # break gracefully
                if cv2.waitKey(10) & 0XFF==ord('q'):
                    break

    cap.release()
    cv2.destroyAllWindows()

c:\Users\gk-lenovo\OneDrive\Desktop\Projects\final_year_project\project_code\venv\lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '


<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti

In [118]:
cap.release()
cv2.destroyAllWindows()

In [128]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [120]:
label_map={label:num for num,label in enumerate(actions)}


In [121]:
label_map

{'hello': 0, 'thanks': 1, 'iloveyou': 2}

In [122]:
sequences,labels=[],[]
for action in actions:
    for sequence in range(no_sequence):
        window=[]
        for frame_num in range(sequence_length):
            res=np.load(os.path.join(DATA_PATH,action,str(sequence),"{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [124]:
np.array(sequences).shape

(90, 30, 1662)

In [125]:
np.array(labels).shape

(90,)

In [126]:
X=np.array(sequences)

In [127]:
X.shape

(90, 30, 1662)

In [129]:
y=to_categorical(labels).astype(int)

In [130]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [131]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.05)

In [135]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense
from tensorflow.keras.callbacks import TensorBoard

In [136]:
log_dir=os.path.join("Logs")
tb_callback=TensorBoard(log_dir=log_dir)

In [137]:
model=Sequential()
model.add(LSTM(64,return_sequences=True,activation='relu',input_shape=(30,1662)))
model.add(LSTM(128,return_sequences=True,activation='relu'))
model.add (LSTM(64,return_sequences=False,activation='relu'))
model.add(Dense(64,activation="relu"))
model.add(Dense(32,activation="relu"))
model.add(Dense(actions.shape[0],activation="softmax"))

c:\Users\gk-lenovo\OneDrive\Desktop\Projects\final_year_project\project_code\venv\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [138]:
model.compile(optimizer="Adam",loss="categorical_crossentropy",metrics=['categorical_accuracy'])

In [139]:
model.fit(X_train,y_train,epochs=1000,callbacks=[tb_callback])

Epoch 1/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 15s 124ms/step - categorical_accuracy: 0.2936 - loss: 4.3530
Epoch 2/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - categorical_accuracy: 0.3249 - loss: 25.0027
Epoch 3/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - categorical_accuracy: 0.4285 - loss: 19.6556
Epoch 4/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - categorical_accuracy: 0.3699 - loss: 36.1496
Epoch 5/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - categorical_accuracy: 0.3639 - loss: 52.8086
Epoch 6/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - categorical_accuracy: 0.3620 - loss: 30.0779
Epoch 7/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - categorical_accuracy: 0.3503 - loss: 11.8207
Epoch 8/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - categorical_accuracy: 0.3601 - loss: 17.7208
Epoch 9/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - categorical_accuracy: 0.3699 - loss: 13.0001
Epoch 10/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - categorical_accuracy: 0.2446 - loss: 9.7324 
Epoch 11/1000

In [140]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30, 64)         │       442,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 30, 128)        │        98,816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,790,027 (6.83 MB)

 Trainable params: 596,675 (2.28 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,193,352 (4.55 MB)

In [142]:
res=model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


In [150]:
actions[np.argmax(res[0])]

'iloveyou'

In [151]:
actions[np.argmax(y_test[0])]

'iloveyou'

In [152]:
model.save("action.h5")

In [154]:
from sklearn.metrics import multilabel_confusion_matrix,accuracy_score

In [161]:
yhat=model.predict(X_train)

3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step


In [162]:
ytrue=np.argmax(y_train,axis=1).tolist()
yhat=np.argmax(yhat,axis=1).tolist()

In [163]:
multilabel_confusion_matrix(ytrue,yhat)

array([[[56,  0],
        [ 0, 29]],

       [[56,  0],
        [ 0, 29]],

       [[58,  0],
        [ 0, 27]]], dtype=int64)

In [164]:
accuracy_score(ytrue,yhat)

1.0

In [169]:
colors = [(245,117,16), (117,245,16), (16,117,245)]
def prob_viz(res, actions, input_frame, colors):
    output_frame = input_frame.copy()
    for num, prob in enumerate(res):
        cv2.rectangle(output_frame, (0,60+num*40), (int(prob*100), 90+num*40), colors[num], -1)
        cv2.putText(output_frame, actions[num], (0, 85+num*40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        
    return output_frame

In [ ]:
sequence = []
sentence = []
threshold = 0.8

cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detect(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)
        
        # 2. Prediction logic
        keypoints = extract_keypoints(results)
#         sequence.insert(0,keypoints)
#         sequence = sequence[:30]
        sequence.append(keypoints)
        sequence = sequence[-30:]
        
        if len(sequence) == 30:
            # Result value
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])
            
            
        #3. Viz logic
            if res[np.argmax(res)] > threshold: 
                if len(sentence) > 0: 
                    if actions[np.argmax(res)] != sentence[-1]:
                        sentence.append(actions[np.argmax(res)])
                else:
                    sentence.append(actions[np.argmax(res)])

            if len(sentence) > 5: 
                sentence = sentence[-5:]

            # Viz probabilities
            image = prob_viz(res, actions, image, colors)
            
        cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
        cv2.putText(image, ' '.join(sentence), (3,30), 
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

In [171]:
cap.release()
cv2.destroyAllWindows()

In [ ]:
cap=cv2.VideoCapture(0)
# Access mediapipe model
with mp_holistic.Holistic(min_detection_confidence=0.5,min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():
        # read feed
        ret,frame=cap.read()

        # make detections
        image,results=mediapipe_detect(frame,holistic)
        print(results)

        # draw landmarks
        draw_styled_landmarks(image,results)

        # show to screen
        cv2.imshow("OpenCV Feed",image)

        # break gracefully
        if cv2.waitKey(10) & 0XFF==ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

<class 'mediapipe.python.solution_base.SolutionOutputs'>


c:\Users\gk-lenovo\OneDrive\Desktop\Projects\final_year_project\project_code\venv\lib\site-packages\google\protobuf\symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '


<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.solution_base.SolutionOutputs'>
<class 'mediapipe.python.soluti